spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  dashboard:
    path: /springui
  instance:
    hostname: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}